CREATE TABLE `blogPosts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(256) NOT NULL,
	`title` varchar(512) NOT NULL,
	`titleTr` varchar(512),
	`titleId` varchar(512),
	`titleRu` varchar(512),
	`excerpt` text,
	`excerptTr` text,
	`excerptId` text,
	`excerptRu` text,
	`content` text NOT NULL,
	`contentTr` text,
	`contentId` text,
	`contentRu` text,
	`category` enum('investment-guide','legal-tax','real-estate','lifestyle','news') NOT NULL,
	`image` varchar(512),
	`author` varchar(128) DEFAULT 'BaseOne Bali Team',
	`metaTitle` varchar(256),
	`metaDescription` text,
	`blogStatus` enum('published','draft') NOT NULL DEFAULT 'draft',
	`publishedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blogPosts_id` PRIMARY KEY(`id`),
	CONSTRAINT `blogPosts_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `vendorSubmissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(256) NOT NULL,
	`description` text,
	`vendorType` enum('villa','commercial','office','land','warehouse') NOT NULL,
	`vendorListingType` enum('rent','sale') NOT NULL,
	`region` varchar(64) NOT NULL,
	`priceUSD` int NOT NULL,
	`area` int NOT NULL,
	`bedrooms` int,
	`bathrooms` int,
	`features` text,
	`imageUrls` text,
	`contactName` varchar(128) NOT NULL,
	`contactEmail` varchar(320) NOT NULL,
	`contactPhone` varchar(32),
	`companyName` varchar(256),
	`vendorStatus` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`odooLeadId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `vendorSubmissions_id` PRIMARY KEY(`id`)
);
